image: node:14

stages:
  - build
  - test
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
      - static
      - package.json
      - .ebextensions
      - .elasticbeanstalk
  before_script:
    - yarn install
  script:
    - yarn build

test:
  stage: test
  cache:
    paths:
      - node_modules
  dependencies:
    - build
  before_script:
    - yarn install
  script:
    - yarn lint
    - yarn test --passWithNoTests

.deploy:
  image: python:latest
  stage: deploy
  allow_failure: false
  dependencies:
    - test
    - build
  before_script:
    - pip install awscli
    - apt-get update -y
    - apt-get install -y zip
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  script:
    - export VERSION_LABEL="${CI_COMMIT_SHA}-$(date +%s)"
    - zip -r "${CI_COMMIT_SHA}.zip" dist static package.json .ebextensions .elasticbeanstalk
    - aws s3 cp "${CI_COMMIT_SHA}.zip" "s3://${AWS_EB_BUCKET_NAME}/${AWS_EB_APP_NAME}/${CI_COMMIT_SHA}.zip"
    - aws elasticbeanstalk create-application-version --application-name "${AWS_EB_APP_NAME}" --version-label "$VERSION_LABEL" --source-bundle S3Bucket="${AWS_EB_BUCKET_NAME}",S3Key="${AWS_EB_APP_NAME}/${CI_COMMIT_SHA}.zip" --region "${AWS_REGION}"
    - aws elasticbeanstalk update-environment --environment-name "${AWS_EB_APP_NAME}-${CI_ENVIRONMENT_NAME}-env" --application-name "${AWS_EB_APP_NAME}" --version-label "$VERSION_LABEL" --region "${AWS_REGION}"

deploy:prod:
  extends: .deploy
  environment:
    name: production
  when: manual
  only:
    - master

deploy:staging:
  extends: .deploy
  environment:
    name: staging
  only:
    - develop
